apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.Values.api.deployment}}"
spec:
  replicas: {{ default 3 .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: smackapi
        version: "{{.Values.api.versionLabel}}"
    spec:
      containers:
      - name: smackapi
        image: "{{.Values.api.image}}:{{.Values.api.imageTag}}"
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: acrregistrykey