apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: prod
spec:
  destination:
    name: smackapi
  route:
  - labels:
      version: new
    weight: 0
  - labels:
      version: prod
    weight: 100