apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: split
spec:
  destination:
    name: smackapi
  route:
  - labels:
      version: new
    weight: 50
  - labels:
      version: newer
    weight: 50