apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: canary
spec:
  destination:
    name: smackapi
  route:
  - labels:
      version: new
    weight: 90
  - labels:
      version: prod
    weight: 50